
# Directory where Inquisitor will watch for changes. Any subdirectories
# within input_directory will become a tag within the json output.
input_directory: input

# Directory where queries with greater than zero hits will be output.
output_directory: output

# A file that contains at least one GitHub token. Tokens do not require any
# privileges, but are required to perform github_search() API calls.
token_file: config/tokenfile

# A file with line-separated terms to add to every query. If your base search term is
# "company" and augmentor contains a line with "ssh" and a line with "jsdb" then two
# queries will be conducted: "company ssh" and "company jsdb"
search_augmentor_file: config/search_augmentor

# A file with a single line containing a string that is added to every query.
# If your base serach term is "company" and an augmentor contains "ssh" and
# your search_parameters file contains "-extension:html", then your query will
# be "company ssh -extension:html"
search_parameters_file: config/search_parameters

# A file containing debug information.
log_file: logs/out.log

# Output file for every query (even if they have zero hits)
querylog_file: logs/queries.log

# Delay in seconds between successive queries per thread. This will need to be higher
# If you are not using a base_url generated by fireprox.
query_delay: 1

# If using fireprox (AWS Gateway API), put base_url here. Defaults to https://api.github.com
#base_url: https://xxxxxxxxx.execute-api.us-east-1.amazonaws.com/fireprox/
